stages:
  - build
  - stage
  - test
  - deploy

image: docker:latest

# Can use UI to hide passwords
variables:
  IMAGE_NAME: hotrod-route
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_USER: willwangkelda
  KUBECTL_URL: https://storage.googleapis.com/kubernetes-release/release/v1.10.3/bin/linux/amd64/kubectl
  KUBE_NAMESPACE: hotrod
  ISTIO_URL: https://github.com/istio/istio/releases/download/0.8.0/istio-0.8.0-linux.tar.gz

services:
  - docker:dind

before_script:
  - apk update && apk add curl bash openssl
  - curl -LO $KUBECTL_URL
  - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
  - curl -L $ISTIO_URL | tar xz
  - mv ./istio-*/bin/istioctl /usr/local/bin/istioctl
  - mkdir -p $HOME/.kube
  - cat $KUBECONFIG > $HOME/.kube/config

build:
  stage: build
  before_script:
  - echo "skip before_script"
  script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

  # Build hotrod image
  - docker pull $DOCKER_USER/$IMAGE_NAME:latest
  - docker build
    -t $DOCKER_USER/$IMAGE_NAME:$CI_COMMIT_SHA
    --cache-from $DOCKER_USER/$IMAGE_NAME:latest
    --build-arg git_pass=$GITLAB_TOKEN
    --build-arg build_time=$(date +%s) .
  - docker push $DOCKER_USER/$IMAGE_NAME:$CI_COMMIT_SHA
  - docker tag $DOCKER_USER/$IMAGE_NAME:$CI_COMMIT_SHA  $DOCKER_USER/$IMAGE_NAME:latest
  - docker push $DOCKER_USER/$IMAGE_NAME:latest

stage:
  stage: stage
  environment:
      name: StageEnv
  script:
    - sed -i -e s/COMMITID/$CI_COMMIT_SHA/g hotrod.yaml
    - sed -i -e s/GITLAB_CI_ENV_SLUG/$CI_ENVIRONMENT_SLUG/g hotrod.yaml
    - sed -i -e s/APPLICATION_TRACK/stable/g hotrod.yaml
    - sed -i -e s/REPLICA_COUNT/3/g hotrod.yaml
    - istioctl kube-inject -f hotrod.yaml -o hotrod-with-istio.yaml
    - kubectl apply -f hotrod-with-istio.yaml --namespace $KUBE_NAMESPACE

unit:
  stage: test
  environment:
    name: StageEnv
  variables:
    KUBERNETES_NAMESPACE_OVERWRITE: hotrod
  script:
    - apk add python py-pip
    - pip install requests
    - kubectl rollout status deployment/$CI_ENVIRONMENT_SLUG-hotrod-route --namespace $KUBE_NAMESPACE
    - python route_unit_test.py

production:
  stage: deploy
  environment:
      name: ProdEnv
  script:
    - sed -i -e s/COMMITID/$CI_COMMIT_SHA/g hotrod.yaml
    - sed -i -e s/GITLAB_CI_ENV_SLUG/$CI_ENVIRONMENT_SLUG/g hotrod.yaml
    - sed -i -e s/APPLICATION_TRACK/stable/g hotrod.yaml
    - sed -i -e s/REPLICA_COUNT/3/g hotrod.yaml
    - istioctl kube-inject -f hotrod.yaml -o hotrod-with-istio.yaml
    - kubectl apply -f hotrod-with-istio.yaml --namespace $KUBE_NAMESPACE
